//go:build ignore

// Gen compiles shader.metal into a Metal library with Xcode's metal tools
// and writes shaderlib.go, so that renderers start without compiling the
// shader, which takes over 100 ms until Metal has cached it. It runs on
// macOS with Xcode: go generate ./internal/gpu/metal
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"log"
	"os"
	"os/exec"
	"path/filepath"

	"github.com/egoist/mygo/internal/gpu"
)

func main() {
	src, err := os.ReadFile("shader.metal")
	if err != nil {
		log.Fatal(err)
	}
	dir, err := os.MkdirTemp("", "metal")
	if err != nil {
		log.Fatal(err)
	}
	defer os.RemoveAll(dir)
	air, lib := filepath.Join(dir, "shader.air"), filepath.Join(dir, "shader.metallib")
	// macOS 12 is the oldest MyGo runs on.
	run("xcrun", "-sdk", "macosx", "metal", "-c", "shader.metal", "-o", air, "-mmacosx-version-min=12.0")
	run("xcrun", "-sdk", "macosx", "metallib", air, "-o", lib)
	code, err := os.ReadFile(lib)
	if err != nil {
		log.Fatal(err)
	}
	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by gen.go from shader.metal; DO NOT EDIT.\n\n//go:build darwin\n\npackage metal\n\n")
	fmt.Fprintf(&b, "// shaderLibrarySum is the SHA-256 of the shader.metal shaderLibrary was\n// compiled from.\nconst shaderLibrarySum = %q\n\n", gpu.SourceSum(string(src)))
	b.WriteString("var shaderLibrary = []byte{")
	for i, c := range code {
		if i%16 == 0 {
			b.WriteString("\n\t")
		}
		fmt.Fprintf(&b, "0x%02x, ", c)
	}
	b.WriteString("\n}\n")
	out, err := format.Source(b.Bytes())
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile("shaderlib.go", out, 0o644); err != nil {
		log.Fatal(err)
	}
}

func run(name string, args ...string) {
	cmd := exec.Command(name, args...)
	cmd.Stdout, cmd.Stderr = os.Stdout, os.Stderr
	if err := cmd.Run(); err != nil {
		log.Fatalf("%s: %v", name, err)
	}
}
